#!/bin/bash

# get load averages
IFS=" " read LOAD1 LOAD5 LOAD15 <<<$(cat /proc/loadavg | awk '{ print $1,$2,$3 }')
# get free memory
IFS=" " read USED AVAIL TOTAL <<<$(free -htm | grep "Mem" | awk {'print $3,$7,$2'})
# get processes
PROCESS=`ps -eo user=|sort|uniq -c | awk '{ print $2 " " $1 }'`
PROCESS_ALL=`echo "$PROCESS"| awk {'print $2'} | awk '{ SUM += $1} END { print SUM }'`
PROCESS_ROOT=`echo "$PROCESS"| grep root | awk {'print $2'}`
PROCESS_USER=`echo "$PROCESS"| grep -v root | awk {'print $2'} | awk '{ SUM += $1} END { print SUM }'`
# colors
blue="\e[1;34m"
green="\e[1;32m"
white="\e[0;39m"

echo -e "
${blue}SYSTEM INFO:
$white  Distro......: $white`cat /etc/*release | grep "PRETTY_NAME" | cut -d "=" -f 2- | sed 's/"//g'`
$white  Kernel......: $white`uname -sr`

$white  Uptime......: $white`uptime -p`
$white  Load........: $green$LOAD1$white (1m), $green$LOAD5$white (5m), $green$LOAD15$white (15m)
$white  Processes...: $green$PROCESS_ROOT$white (root), $green$PROCESS_USER$white (user), $green$PROCESS_ALL$white (total)
$white  Memory......: $green$USED$white used, $green$AVAIL$white avail, $green$TOTAL$white total"
