---
- name: Configure the Server and install required software
# ========================================================
  hosts: wormhole

  become: true

  roles:
  - { role: common,       tags: ['common'] }
  - { role: ssh,          tags: ['ssh'] }
  - { role: ufw,          tags: ['ufw'] }
  - { role: nginx,        tags: ['nginx'] }
  - { role: ssl,          tags: ['ssl'] }
  - { role: uwsgi,        tags: ['uwsgi'] }
  - { role: nextcloud,    tags: ['nextcloud'] }
  - { role: wireguard,    tags: ['wireguard'] }
  - { role: shadowsocks,  tags: ['shadowsocks', 'never'] }
