---
nextcloud_admin: nextcloud
nextcloud_admin_email: nextcloud@example.com

nextcloud_apps:
  - calendar
  - contacts
  - maps
  - news
  - twofactor_nextcloud_notification
  - twofactor_totp
nextcloud_apps_disable:
  - encryption
  - federation
  - files_external
  - files_pdfviewer
  - files_videoplayer
  - firstrunwizard
  - photos
  - support
  - survey_client
  - systemtags
  - user_ldap

nextcloud_base_group: 'users'
nextcloud_base_user: 'user'

nextcloud_domain: 'cloud.{{ common_hostname }}'

nextcloud_file_config: '{{ nextcloud_path_webroot }}/config/config.php'
nextcloud_file_password: '{{ nextcloud_path }}/password.txt'
nextcloud_file_source_code: '{{ nextcloud_path }}/latest.tar.bz2'

nextcloud_path: /opt/nextcloud
nextcloud_path_webroot: /var/www/nextcloud
nextcloud_path_data: '{{ nextcloud_path_webroot }}/data'

nextcloud_php_packages:
  - php-apcu
  - 'php{{ nextcloud_php_version }}-bz2'
  - 'php{{ nextcloud_php_version }}-curl'
  - 'php{{ nextcloud_php_version }}-gd'
  - 'php{{ nextcloud_php_version }}-intl'
  - 'php{{ nextcloud_php_version }}-mbstring'
  - 'php{{ nextcloud_php_version }}-sqlite3'
  - 'php{{ nextcloud_php_version }}-xml'
  - 'php{{ nextcloud_php_version }}-zip'
nextcloud_php_version: 7.2

nextcloud_uwsgi_sock: '{{ uwsgi_path_socks }}/nextcloud/socket'
