---
- name: Install package
  apt:
    package: ufw

- name: Disable logging
  lineinfile:
    dest: /etc/ufw/ufw.conf
    regexp: '^LOGLEVEL'
    line: 'LOGLEVEL=off'

- name: Change the default forward policy
  lineinfile:
    dest: /etc/default/ufw
    regexp: '^DEFAULT_FORWARD_POLICY'
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'

- name: Ensure allows HTTP/S
  ufw:
    port: '{{ item }}'
    proto: tcp
    rule: allow
  with_items: [http, https]

- name: Ensure allows Shadowsocks
  ufw:
    to_port: '{{ shadowsocks_conf.server_port }}'
    proto: any
    rule: allow

- name: Ensure limits SSH
  ufw:
    port: ssh
    proto: tcp
    rule: limit

- name: Ensure is enabled and denies by default
  ufw:
    direction: incoming
    policy: deny
    state: enabled
