---
- name: Get ACME.sh installer
  get_url:
    url: https://get.acme.sh
    dest: /root/installer.acme.sh
    mode: 0500

- name: Install ACME.sh
  shell:  /root/installer.acme.sh

- name: Create required directories
  file:
    path: '{{ item }}'
    group: '{{ nginx_group }}'
    owner: '{{ nginx_user }}'
    state: directory
  with_items:
    - '{{ ssl_path_domain }}'
    - '{{ nginx_path_webroot }}/.well-known'

- name: Issue certificates
  shell: '{{ ssl_acme_sh }} --issue -d {{ ssl_domain }} -d www.{{ ssl_domain }} -w {{ nginx_path_webroot }}'

- name: Generate Diffie-Hellman Group
  openssl_dhparam:
    out: '{{ ssl_path }}/dhparams.pem'
    size: 3096

- name: Install certificates
  shell: >
    {{ ssl_acme_sh }} --install-cert -d {{ ssl_domain }} \
                  --fullchain-file  {{ ssl_path_domain }}/fullchain.pem \
                  --key-file        {{ ssl_path_domain }}/key.pem \
                  --reloadcmd       "service nginx force-reload"

- name: Ensure certificates right owner
  file:
    name: '{{ ssl_path }}'
    group: '{{ nginx_group }}'
    owner: '{{ nginx_user }}'
    recurse: yes

- name: Add new config for default vhost
  template:
    src: default.conf.j2
    dest: '{{ nginx_path_vhost }}'
    group: '{{ nginx_group }}'
    owner: '{{ nginx_user }}'
  notify: nginx restarted
