---
- name: Add how-to create new clients
  template:
    src: README.md.j2
    dest: '{{ wireguard_path_clients }}/README.md'
    mode: 0644

- name: Add template for new clients
  template:
    src: client.conf.tpl.j2
    dest: '{{ wireguard_path_clients }}/client.conf.tpl'
    mode: 0644
